<h1><?php echo $this->pageTitle; ?></h1>
<table class="table">
	<thead>
		<tr>
			<th>Nom</th>
			<th colspan="2">&nbsp;</th>
		</tr>
	</thead>
	<tbody>
<?php
if( $this->entries->count() > 0 ) :
	$i = 0;
	foreach( $this->entries as $entry ) :
?>
		    <tr class="<?php echo ( $i % 2 == 0 ? 'impair' : 'pair' ); ?>">
		    	<td><?php echo $this->escape( $entry->name ); ?></td>
		    	<td>
		    		<a href="<?php echo $this->link( 'enseigne', 'edit', null, array( 'id' => $entry->id ) );?>">Éditer</a>
		    	</td>
		    	<td>
		    		<a href="<?php echo $this->link( 'enseigne', 'delete', null, array( 'id' => $entry->id ) );?>">Supprimer</a>
		    	</td>
		    </tr>
<?php
		$i++;
	endforeach;
else :
?>
		<tr>
			<td colspan="3" class="nodata"><?php echo $this->translate( "No data" ); ?></td>
		</tr>
<?php endif;?>
	</tbody>
</table>